version: '3.8'
services:
  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.7.0
    command:
    - --kafka.server=10.11.12.60:9092
    - --kafka.server=10.11.12.61:9092
    - --kafka.server=10.11.12.62:9092
    restart: always
    network_mode: host
    # ports:
    # - 9308:9308
    volumes:
    - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
