version: '3.8'
services:
  nexus3:
    image: sonatype/nexus3:3.59.0
    restart: always
    environment:
      INSTALL4J_ADD_VM_PARAMS: >-
        -Xms100m
        -Xmx1024m
        -XX:MaxDirectMemorySize=1024m
    ports:
    - 8081:8081
    volumes:
    - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    - ./nexus-data:/nexus-data
